// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@2.0.4";

// src/lib/mcp/tools/list-inventory.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.112.3";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-inventory.ts
var list_inventory_default = defineTool({
  name: "list_inventory",
  title: "Consultar estoque",
  description: "Lista o estoque da casa (marca, modelo, sabor, pre\xE7o de venda e quantidade), com filtros opcionais por marca/modelo/sabor e por estoque baixo.",
  inputSchema: {
    brand: z.string().optional().describe("Filtra pela marca (busca parcial)."),
    model: z.string().optional().describe("Filtra pelo modelo (busca parcial)."),
    flavor: z.string().optional().describe("Filtra pelo sabor (busca parcial)."),
    only_low_stock: z.boolean().optional().describe("Se verdadeiro, retorna apenas itens com estoque igual ou abaixo do m\xEDnimo."),
    limit: z.number().int().optional().describe("M\xE1ximo de linhas (padr\xE3o 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ brand, model, flavor, only_low_stock, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("products").select("id, brand, model, flavor, sale_price, stock, min_stock").order("brand").order("model").order("flavor").limit(Math.min(Math.max(limit ?? 100, 1), 500));
    if (brand) query = query.ilike("brand", `%${brand}%`);
    if (model) query = query.ilike("model", `%${model}%`);
    if (flavor) query = query.ilike("flavor", `%${flavor}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = (data ?? []).filter((r) => only_low_stock ? r.stock <= r.min_stock : true);
    return {
      content: [{ type: "text", text: JSON.stringify(rows) }],
      structuredContent: { count: rows.length, products: rows }
    };
  }
});

// src/lib/mcp/tools/list-pending-orders.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z2 } from "npm:zod@^3.25.76";
var list_pending_orders_default = defineTool2({
  name: "list_pending_orders",
  title: "Pedidos pendentes",
  description: "Lista os pedidos feitos pelo cat\xE1logo que ainda aguardam confirma\xE7\xE3o, com cliente, vendedor, valor e itens.",
  inputSchema: {
    limit: z2.number().int().optional().describe("M\xE1ximo de pedidos (padr\xE3o 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("orders").select(
      "id, status, total_amount, freight_notes, created_at, customers(name, whatsapp), sellers(name), order_items(quantity, unit_price, products(brand, model, flavor))"
    ).eq("status", "pendente").order("created_at", { ascending: false }).limit(Math.min(Math.max(limit ?? 20, 1), 100));
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const orders = data ?? [];
    return {
      content: [{ type: "text", text: JSON.stringify(orders) }],
      structuredContent: { count: orders.length, orders }
    };
  }
});

// src/lib/mcp/tools/sales-summary.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z3 } from "npm:zod@^3.25.76";
var sales_summary_default = defineTool3({
  name: "sales_summary",
  title: "Resumo de vendas",
  description: "Resumo das vendas em um per\xEDodo: quantidade de vendas, unidades, receita total, valor j\xE1 recebido e valor em aberto.",
  inputSchema: {
    start_date: z3.string().describe("Data inicial no formato AAAA-MM-DD."),
    end_date: z3.string().describe("Data final no formato AAAA-MM-DD (inclusiva)."),
    seller_name: z3.string().optional().describe("Filtra por nome do vendedor (busca parcial).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ start_date, end_date, seller_name }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let sellerIds = null;
    if (seller_name) {
      const { data: sellers, error: sellersError } = await supabase.from("sellers").select("id").ilike("name", `%${seller_name}%`);
      if (sellersError) {
        return { content: [{ type: "text", text: sellersError.message }], isError: true };
      }
      sellerIds = (sellers ?? []).map((s) => s.id);
      if (sellerIds.length === 0) {
        return {
          content: [{ type: "text", text: "Nenhum vendedor encontrado com esse nome." }],
          isError: true
        };
      }
    }
    let query = supabase.from("sales").select("quantity, total_price, paid_amount, type").gte("date", start_date).lte("date", end_date);
    if (sellerIds) query = query.in("seller_id", sellerIds);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    const summary = rows.reduce(
      (acc, r) => {
        acc.sales += 1;
        acc.units += r.quantity;
        acc.revenue += Number(r.total_price);
        acc.received += Number(r.paid_amount);
        return acc;
      },
      { sales: 0, units: 0, revenue: 0, received: 0 }
    );
    const result = {
      period: { start_date, end_date },
      seller_name: seller_name ?? null,
      ...summary,
      outstanding: Number((summary.revenue - summary.received).toFixed(2))
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/seller-stock.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z4 } from "npm:zod@^3.25.76";
var seller_stock_default = defineTool4({
  name: "seller_stock",
  title: "Estoque com vendedores",
  description: "Mostra quanto de cada produto est\xE1 atribu\xEDdo a cada vendedor (consigna\xE7\xE3o), opcionalmente filtrado por vendedor.",
  inputSchema: {
    seller_name: z4.string().optional().describe("Filtra por nome do vendedor (busca parcial)."),
    limit: z4.number().int().optional().describe("M\xE1ximo de linhas (padr\xE3o 200).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ seller_name, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("product_assignments").select("quantity, sellers(name), products(brand, model, flavor, sale_price)").gt("quantity", 0).limit(Math.min(Math.max(limit ?? 200, 1), 500));
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const needle = seller_name?.trim().toLowerCase();
    const sellerNameOf = (row) => {
      const rel = row.sellers;
      const first = Array.isArray(rel) ? rel[0] : rel;
      return first?.name ?? "";
    };
    const rows = (data ?? []).filter(
      (r) => needle ? sellerNameOf(r).toLowerCase().includes(needle) : true
    );
    return {
      content: [{ type: "text", text: JSON.stringify(rows) }],
      structuredContent: { count: rows.length, assignments: rows }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "qojybnnwxmxmqahmjxiy";
var mcp_default = defineMcp({
  name: "california",
  title: "California",
  version: "0.1.0",
  instructions: "Ferramentas do California (gest\xE3o de estoque, vendas e consigna\xE7\xE3o). Use `list_inventory` para consultar estoque e itens em falta, `seller_stock` para o que est\xE1 com cada vendedor, `list_pending_orders` para pedidos do cat\xE1logo aguardando confirma\xE7\xE3o e `sales_summary` para totais de vendas em um per\xEDodo.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_inventory_default, seller_stock_default, list_pending_orders_default, sales_summary_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@2.0.4/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
